"""Generate deterministic BUSI split files from manifest.csv."""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path
import random
import sys

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from busi_seg.data.manifest import read_manifest, write_split_ids

TRAIN_SPLIT = "train.txt"
VAL_SPLIT = "val.txt"
TEST_SPLIT = "test.txt"
LABELED_SUBSET_SPLIT = "labeled_subset.txt"
UNLABELED_POOL_SPLIT = "unlabeled_pool.txt"
OVERFIT_SPLIT = "overfit_8_samples.txt"
SMOKE_LABELED_SPLIT = "smoke_labeled.txt"
SMOKE_UNLABELED_SPLIT = "smoke_unlabeled.txt"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate deterministic BUSI split files from manifest.csv."
    )
    parser.add_argument(
        "--manifest-path",
        type=Path,
        default=Path("data_meta/manifest.csv"),
        help="Path to manifest.csv generated by prepare_busi_manifest.py.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data_meta/splits/seed0"),
        help="Directory where split text files will be written.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=0,
        help="Random seed used for deterministic split generation.",
    )
    parser.add_argument(
        "--labeled-fraction",
        type=float,
        default=0.2,
        help="Fraction of train sample_ids to include in labeled_subset.txt.",
    )
    parser.add_argument(
        "--val-fraction",
        type=float,
        default=0.15,
        help="Fraction of total sample_ids to include in val.txt.",
    )
    parser.add_argument(
        "--test-fraction",
        type=float,
        default=0.15,
        help="Fraction of total sample_ids to include in test.txt.",
    )
    parser.add_argument(
        "--overfit-count",
        type=int,
        default=8,
        help="Number of sample_ids to put into overfit_8_samples.txt.",
    )
    parser.add_argument(
        "--smoke-labeled-count",
        type=int,
        default=4,
        help="Number of labeled sample_ids for ssl_smoke_test.",
    )
    parser.add_argument(
        "--smoke-unlabeled-count",
        type=int,
        default=8,
        help="Number of unlabeled sample_ids for ssl_smoke_test.",
    )
    return parser.parse_args()


def ensure_output_dir(output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)


def _deterministic_shuffle(values: list[str], seed: int) -> list[str]:
    shuffled = list(values)
    rng = random.Random(seed)
    rng.shuffle(shuffled)
    return shuffled


def _split_group(
    sample_ids: list[str], *, val_fraction: float, test_fraction: float
) -> tuple[list[str], list[str], list[str]]:
    total = len(sample_ids)
    test_count = int(round(total * test_fraction))
    val_count = int(round(total * val_fraction))
    if val_count + test_count >= total:
        overflow = val_count + test_count - total + 1
        if test_count >= val_count:
            test_count = max(0, test_count - overflow)
        else:
            val_count = max(0, val_count - overflow)

    train_count = total - val_count - test_count
    train_ids = sample_ids[:train_count]
    val_ids = sample_ids[train_count : train_count + val_count]
    test_ids = sample_ids[train_count + val_count :]
    return train_ids, val_ids, test_ids


def _stratified_train_val_test(
    *,
    label_map: dict[str, str],
    seed: int,
    val_fraction: float,
    test_fraction: float,
) -> tuple[list[str], list[str], list[str]]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for sample_id, label_group in label_map.items():
        grouped[label_group].append(sample_id)

    train_ids: list[str] = []
    val_ids: list[str] = []
    test_ids: list[str] = []

    for label_index, label_group in enumerate(sorted(grouped)):
        shuffled = _deterministic_shuffle(sorted(grouped[label_group]), seed + label_index)
        group_train, group_val, group_test = _split_group(
            shuffled,
            val_fraction=val_fraction,
            test_fraction=test_fraction,
        )
        train_ids.extend(group_train)
        val_ids.extend(group_val)
        test_ids.extend(group_test)

    return sorted(train_ids), sorted(val_ids), sorted(test_ids)


def _stratified_labeled_subset(
    *,
    train_ids: list[str],
    label_map: dict[str, str],
    seed: int,
    labeled_fraction: float,
) -> list[str]:
    grouped: dict[str, list[str]] = defaultdict(list)
    for sample_id in train_ids:
        grouped[label_map[sample_id]].append(sample_id)

    subset: list[str] = []
    for label_index, label_group in enumerate(sorted(grouped)):
        shuffled = _deterministic_shuffle(
            sorted(grouped[label_group]),
            seed + 100 + label_index,
        )
        select_count = int(round(len(shuffled) * labeled_fraction))
        if labeled_fraction > 0.0 and shuffled:
            select_count = max(1, select_count)
        select_count = min(len(shuffled), select_count)
        subset.extend(shuffled[:select_count])

    return sorted(subset)


def _take_first_n(sample_ids: list[str], count: int, seed: int) -> list[str]:
    shuffled = _deterministic_shuffle(sorted(sample_ids), seed)
    return sorted(shuffled[: min(count, len(shuffled))])


def main() -> None:
    args = parse_args()
    if args.val_fraction < 0.0 or args.test_fraction < 0.0:
        raise ValueError("val_fraction and test_fraction must be non-negative.")
    if args.val_fraction + args.test_fraction >= 1.0:
        raise ValueError("val_fraction + test_fraction must be < 1.0.")
    if not 0.0 <= args.labeled_fraction <= 1.0:
        raise ValueError("labeled_fraction must be within [0, 1].")

    ensure_output_dir(args.output_dir)
    manifest = read_manifest(args.manifest_path)
    label_map = manifest.label_map()

    train_ids, val_ids, test_ids = _stratified_train_val_test(
        label_map=label_map,
        seed=args.seed,
        val_fraction=args.val_fraction,
        test_fraction=args.test_fraction,
    )
    labeled_subset_ids = _stratified_labeled_subset(
        train_ids=train_ids,
        label_map=label_map,
        seed=args.seed,
        labeled_fraction=args.labeled_fraction,
    )
    unlabeled_pool_ids = sorted(set(train_ids) - set(labeled_subset_ids))
    overfit_ids = _take_first_n(train_ids, args.overfit_count, args.seed + 200)
    smoke_labeled_ids = _take_first_n(
        labeled_subset_ids, args.smoke_labeled_count, args.seed + 300
    )
    smoke_unlabeled_ids = _take_first_n(
        unlabeled_pool_ids, args.smoke_unlabeled_count, args.seed + 400
    )

    write_split_ids(args.output_dir / TRAIN_SPLIT, train_ids)
    write_split_ids(args.output_dir / VAL_SPLIT, val_ids)
    write_split_ids(args.output_dir / TEST_SPLIT, test_ids)
    write_split_ids(args.output_dir / LABELED_SUBSET_SPLIT, labeled_subset_ids)
    write_split_ids(args.output_dir / UNLABELED_POOL_SPLIT, unlabeled_pool_ids)
    write_split_ids(args.output_dir / OVERFIT_SPLIT, overfit_ids)
    write_split_ids(args.output_dir / SMOKE_LABELED_SPLIT, smoke_labeled_ids)
    write_split_ids(args.output_dir / SMOKE_UNLABELED_SPLIT, smoke_unlabeled_ids)


if __name__ == "__main__":
    main()
